server:
  port: 9999

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        provider:
          client:
            issuer-uri: http://localhost:9000
        #            authorization-uri: http://localhost:9000/oauth2/authorize
        #            token-uri: http://localhost:9000/oauth2/token
        #            user-info-uri: http://localhost:9000/userinfo
        #            user-name-attribute: sub
        registration:
          client:
            provider: client
            client-id: client
            client-name: client
            client-secret: client
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9999/login/oauth2/code/client
            scope: read,write,openid
#          github:
#            client-name: Github
#            client-id: 03c2848fb943cb18ec63
#            client-secret: 923990158137b3a58e1166605938bd1d16886f99
#            redirect-uri: http://127.0.0.1:9999/login/oauth2/code/github
#            scope:
#              - user:email
#              - read:user
