server:
  port: 8080

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 03c2848fb943cb18ec63
#            client-secret: 923990158137b3a58e1166605938bd1d16886f99
#            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/github
#            scope:
#              - user:email
#              - read:user
#          zeus:
#            provider: zeus
#            client-id: zeus
#            client-secret: zeus
#            redirect-uri: http://auth-client:8080/login/oauth2/code/zeus
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            scope:
#              - all
#        provider:
#          zeus:
#            authorization-uri: http://auth-server:9000/oauth2/authorize
#            token-uri: http://auth-server:9000/oauth2/token
#            user-info-uri: http://auth-server:9000/userinfo
#            jwk-set-uri: http://auth-server:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: debug
    org.springframework.web.client: debug
