server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "zeus"
              client-secret: "{noop}zeus"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/zeus"
                - "https://www.alexchen.tech"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - all
                - "openid"
                - "profile"
            require-authorization-consent: true